
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://falconur.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Nuriddin Kamardinov"
title: "Nuriddin Kamardinov"
description: "Blog and website of Nuriddin Kamardinov. Opinions expressed are mine."
keywords: "kamardinov, nuriddin, personal, uzbekistan, developer, software-development, software"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black_favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Welcome to personal web-site of Nuriddin Kamardinov"
  - text: "Stop dreaming, start coding"

me-img: "/img/author2.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: True

disqus-shortname: "kamardinov"

syntax-highlight: True

############
# Employment #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "March 2019 - Today"
    description: "Web Developer <br> FREELANCER"
  - image: "/img/timeline/zerone.png"
    date: "October 2018 - February 2019"
    description: "Software Developer <br> ZERONE LLC"
  - image: "/img/timeline/boostin.png"
    date: "June 2018 - September 2018"
    description: "Software Developer <br> BOOSTIN LLC"
  - image: "/img/timeline/gerb.jpeg"
    date: "February 2018 - April 2018"
    description: "Internship <br> THE STATE INSPECTION FOR SUPERVISION OF QUALITY IN EDUCATION"              

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "nuriddinkamardinov@yandex.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
# author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook-f"
    url: "https://www.facebook.com/people/Nuriddin-Kamardinov/100009207819032"
  - title: "twitter"
    url: "https://twitter.com/NKamardinov"
  - title: "linkedin-in"
    url: "https://www.linkedin.com/in/nuriddin-kamardinov/"
  - title: "instagram"
    url: "https://www.instagram.com/n.kamardinov/"
  - title: "vk"
    url: "https://vk.com/nuriddinkamardinov"
  - title: "github"
    url: "https://github.com/falconur"
  - title: "telegram-plane"
    url: "https://www.t.me/falconur"
  - title: "whatsapp"
    url: "https://wa.me/998905433722"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Employment: 'employment'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji